# Project: bim
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = data.o main.o bimg.o
LINKOBJ  = data.o main.o bimg.o
LIBS     = -L"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib" -L"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/KIT.PORT/Orwell Dev-C++ 5.9.2 MinGW 64/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = bim.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

data.o: data.c
	$(CC) -c data.c -o data.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

bimg.o: bimg.c
	$(CC) -c bimg.c -o bimg.o $(CFLAGS)
